# Spring application properties
spring:
  application:
    name: randomquotes-hxsc

# Server context path and port
server:
  servlet:
    context-path: /randomquotes-hxsc
  port: '8081'

# Random quotes api
randomquotes:
  api:
    url: 'https://thequoteshub.com/api/random-quote?format'

# Spring docs api url path
springdoc:
  api-docs:
    path: /api-docs
